### ISSUE TITLE
NuGet packages for Microsoft.Analytics.xxx

### ISSUE THREAD

**Issue by isaacabraham** [Azure/AzureDataLake#23]
Any chance that you will be providing nuget packages for the core Microsoft.Analytics.xxx assemblies rather than having to install tooling to get at them?

**Comment by tomkerkhove** [comment]
What's the status of this one? Is everything included in [this NuGet package](https://www.nuget.org/packages/Microsoft.Azure.DataLake.USQL.SDK/) nowadays?

**Comment by tomkerkhove** [comment]
Think this one can be closed @MikeRys & @saveenr?

**Comment by saveenr** [comment]
Yes; Will close.

https://www.nuget.org/packages/Microsoft.Azure.DataLake.USQL.Interfaces/
